version: "3.9"
services:

  server:
    build: ./server
    ports:
      - "80:5000"
    volumes:
      - ./server:/main
    environment:
      FLASK_ENV: development
      POSTGRES_DB: /server/${POSTGRES_DB}
      POSTGRES_PASSWORD: /server/${POSTGRES_PASSWORD}
    links: 
      - postgres
    depends_on:
      - postgres
    container_name: server

  postgres:
      image: postgres:11-alpine
      restart: always
      environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
          - .postgres-data:/var/lib/postgresql/data
      container_name: database

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    depends_on:
      - server
    container_name: client